---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: osx_yosemite
    driver:
      box: osx_yosemite
      gui: true
      provider: vmware_fusion
      ssh:
        insert_key: false

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    attributes:
