---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: test-osx
    driver:
      box: test-osx
      gui: true

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[workstation::ssh]
    attributes:
