---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.0.3

platforms:
  - name: osx_yosemite
    driver:
      box: osx_yosemite
      gui: true
      provider: vmware_fusion
      ssh:
        insert_key: false
      customize:
        memory: 4096

suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    attributes:
