---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: high-sierra
    driver:
      box: mattstratton/osx_high_sierra
      gui: true

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[workstation::default]
      # - recipe[workstation::tmux]
    attributes:
