name 'workstation'
maintainer 'Matt Stratton'
maintainer_email 'matt.stratton@gmail.com'
license 'apache2'
description 'Installs/Configures an OS X workstation for Matt Stratton'
long_description 'Installs/Configures an OS X workstation for Matt Stratton'
version '0.4.6'

depends 'git','~> 8.0.0'
depends 'homebrew', '~> 4.2.0'
depends 'chef-dk', '~> 3.1.0'
depends 'mac-app-store', '~> 3.1.0'
depends 'chef-vault'
