name 'workstation'
maintainer 'Matt Stratton'
maintainer_email 'matt.stratton@gmail.com'
license 'apache2'
description 'Installs/Configures an OS X workstation for Matt Stratton'
long_description 'Installs/Configures an OS X workstation for Matt Stratton'
version '0.3.23'

depends 'git', '~> 4.2.2'
depends 'homebrew', '~> 2.1.0'
depends 'chef-dk', '~> 3.1.0'
depends 'mac-app-store', '~> 1.2.0'
