default['workstation']['user'] = 'vagrant'
default['mac_app_store']['apps'] = [
    'DaisyDisk',
    'Xcode',
    'Keynote',
    'Fantastical 2',
    'UlyssesMac',
    'Microsoft Remote Desktop',
    '1Password',
    'iMovie',
    'Airmail 3',
    'SnippetsLab',
    'Tweetbot',
    'Bear',
    'Quiver',
    'MindNode',
    'Yoink',
    'Vitamin-R 2',
    'Deckset',
]
default['workstation']['cask'] = [
    'adobe-creative-cloud', 
    'alfred', 
    'atom', 
    'audio-hijack', 
    'bartender', 
    'beyond-compare', 
    'dropbox', 
    'firefox', 
    'font-inconsolata', 
    'gitify', 
    'google-photos-backup-and-sync', 
    'iterm2', 
    'java', 
    'keyboard-maestro', 
    'little-snitch', 
    'microsoft-office', 
    'moom', 
    'ngrok', 
    'postman', 
    'robo-3t', 
    'skitch', 
    'skype', 
    'textexpander', 
    'tower', 
    'vagrant', 
    'virtualbox', 
    'visual-studio-code', 
    'witch',
]
default['workstation']['homebrew'] = [
    'ansible',
    'asciinema',
    'autojump',
    'awscli',
    'bazaar',
    'bfg',
    'bower',
    'cowsay',
    'curl',
    'delve',
    'dep',
    'dirmngr',
    'doxygen',
    'exercism',
    'ffmpeg',
    'fftw',
    'fontconfig',
    'fortune',
    'freetype',
    'git',
    'git-extras',
    'gnupg',
    'go',
    'graphicsmagick',
    'graphite2',
    'graphviz',
    'hub',
    'hugo',
    'imagemagick',
    'jq',
    'lua',
    'luajit',
    'ncurses',
    'node',
    'openssl',
    'packer',
    'perl',
    'ponysay',
    'poppler',
    'python3',
    'readline',
    'ruby',
    'rust',
    'sbt',
    'speedtest-cli',
    'thefuck',
    'tmux',
    'tree',
    'vim',
    'vips',
    'webp',
    'wget',
    'youtube-dl',
    'zsh',
    'zsh-completions',
    'zsh-syntax-highlighting',
]
default['workstation']['teamocil'] = ['ado-hugo', 'bwedding', 'dod']
default['workstation']['git']['name'] = 'Matt Stratton'
default['workstation']['git']['email'] = 'matt.stratton@gmail.com'
default['workstation']['chef']['user'] = 'mattstratton'
default['workstation']['chef']['chef_server_url'] = 'https://api.chef.io/organizations/matt-stratton-personal'
